export * from './types'
export * from './state'
export * from './events'
export * from './evolve'
export * from './decide'
export * from './selectors'
export * from './villageStore'
export * from './VillageEventBus'
export * from './VillageContext'
export * from './VillageProvider'
export * from './useVillageState'

// Re-export commonly used combinations
export type { VillageState } from './state'
export { initialVillageState } from './state'
export type { VillageEvent } from './events'
export type { VillageCommand } from './decide'
export type { Village, VillageWord, VillageContribution, VillageBattle, VillageStats } from './types'
export { villageStore, createVillageStore } from './villageStore'
export { villageEventBus, createVillageEventEnvelope, type VillageEventEnvelope, type IVillageEventBus } from './VillageEventBus'
export { useVillageStore, useVillageIdentity } from './VillageContext'
export { useVillageState } from './useVillageState'
export { VillageProvider } from './VillageProvider'
