/**
 * AI Integration Module
 * 
 * Wires up AI agents with the event-sourcing system following the
 * Event-Driven Architecture Blueprint. Provides tenant-isolated
 * agent management and event stream processing.
 */

import type { GameEvent, GameEventType } from '@/entities/game'
import type { EventEnvelope, EventStore } from '@/shared/event-sourcing'
import type { AIAgent, EventContext, RAGContextBuilder } from '../agent'
import { AdaptiveDifficultyAgent, createAdaptiveDifficultyAgent } from '../agents/adaptiveDifficultyAgent'
import { WhisperAgent, createWhisperAgent } from '../agents/whisperAgent'
import { ElevenLabsAgent, createElevenLabsAgent } from '../agents/elevenLabsAgent'

/**
 * AI Agent Manager
 * 
 * Manages multiple AI agents with proper tenant isolation.
 * Each tenant gets their own agent instances to ensure
 * data privacy and personalized behavior.
 */
export class AIAgentManager {
  private readonly agents = new Map<string, Map<string, AIAgent>>() // tenant_id → aggregate_id → agent
  private readonly eventStore: EventStore<any, GameEvent>
  private readonly globalAgents: AIAgent[] = []

  constructor(eventStore: EventStore<any, GameEvent>) {
    this.eventStore = eventStore
    this.initializeGlobalAgents()
  }

  /**
   * Initialize global agents that can be shared across tenants
   */
  private initializeGlobalAgents(): void {
    // Create adaptive difficulty agent
    const adaptiveAgent = createAdaptiveDifficultyAgent()
    adaptiveAgent.setEventStore(this.eventStore)
    this.globalAgents.push(adaptiveAgent)

    // Create whisper agent for speech-to-text
    const whisperAgent = createWhisperAgent()
    whisperAgent.setEventStore(this.eventStore)
    this.globalAgents.push(whisperAgent)

    // Create elevenlabs agent for text-to-speech
    const elevenLabsAgent = createElevenLabsAgent()
    elevenLabsAgent.setEventStore(this.eventStore)
    this.globalAgents.push(elevenLabsAgent)

    console.log('🤖 [AI] Initialized global agents:', this.globalAgents.map(a => a.name))
  }

  /**
   * Get or create an agent instance for a specific tenant and aggregate
   */
  getAgent(tenant_id: string, aggregate_id: string, agentType: 'adaptive-difficulty' | 'whisper' | 'elevenlabs'): AIAgent {
    // Get tenant-specific agent map
    if (!this.agents.has(tenant_id)) {
      this.agents.set(tenant_id, new Map())
    }

    const tenantAgents = this.agents.get(tenant_id)!

    // Return existing agent if available
    if (tenantAgents.has(aggregate_id)) {
      return tenantAgents.get(aggregate_id)!
    }

    // Create new agent instance for this tenant/aggregate
    let agent: AIAgent
    switch (agentType) {
      case 'adaptive-difficulty':
        agent = createAdaptiveDifficultyAgent()
        break
      default:
        throw new Error(`Unknown agent type: ${agentType}`)
    }

    // Inject event store and store the agent
    agent.setEventStore(this.eventStore)
    tenantAgents.set(aggregate_id, agent)

    console.log(`🤖 [AI] Created ${agent.name} for tenant: ${tenant_id}, aggregate: ${aggregate_id}`)
    return agent
  }

  /**
   * Process events through AI agents for a specific tenant
   */
  async processEvents(tenant_id: string, aggregate_id: string, events: readonly EventEnvelope<GameEvent>[]): Promise<void> {
    if (events.length === 0) return

    console.log(`🤖 [AI] Processing ${events.length} events for tenant: ${tenant_id}`)

    // Build event context using RAG context builder
    const context: EventContext = {
      tenant_id,
      aggregate_id,
      eventHistory: events,
      timestamp: Date.now(),
      metadata: {
        eventCount: events.length,
        lastEventTimestamp: events[events.length - 1]?.timestamp
      }
    }

    // Process through each global agent
    for (const agent of this.globalAgents) {
      await this.processAgent(agent, context)
    }

    // Process through tenant-specific agents
    const tenantAgents = this.agents.get(tenant_id)
    if (tenantAgents && tenantAgents.has(aggregate_id)) {
      const agent = tenantAgents.get(aggregate_id)!
      await this.processAgent(agent, context)
    }
  }

  /**
   * Process events through a single agent
   */
  private async processAgent(agent: AIAgent, context: EventContext): Promise<void> {
    try {
      // Check if agent is subscribed to any of the event types
      const eventTypes = new Set(context.eventHistory.map(e => e.event.type))
      const subscribedTypes = agent.getSubscribedEventTypes()
      
      const hasRelevantEvents = subscribedTypes.some(type => eventTypes.has(type))
      if (!hasRelevantEvents) {
        return // Agent not interested in these events
      }

      // Let the agent process the events
      const newEvents = agent.process(context)

      // Emit any new events generated by the agent
      if (newEvents.length > 0) {
        console.log(`🤖 [AI] ${agent.name} emitting ${newEvents.length} events`)
        agent.emit(newEvents, context.tenant_id, context.aggregate_id)
      }
    } catch (error) {
      console.error(`🤖 [AI] Error in ${agent.name}:`, error)
    }
  }

  /**
   * Get statistics about agent usage
   */
  getStats(): {
    totalTenants: number
    totalAgents: number
    globalAgents: number
    agentsByTenant: Record<string, number>
  } {
    const agentsByTenant: Record<string, number> = {}
    let totalAgents = 0

    for (const [tenant_id, tenantAgents] of this.agents) {
      const count = tenantAgents.size
      agentsByTenant[tenant_id] = count
      totalAgents += count
    }

    return {
      totalTenants: this.agents.size,
      totalAgents,
      globalAgents: this.globalAgents.length,
      agentsByTenant
    }
  }

  /**
   * Cleanup agents for a specific tenant
   */
  cleanupTenant(tenant_id: string): void {
    const removed = this.agents.delete(tenant_id)
    if (removed) {
      console.log(`🤖 [AI] Cleaned up agents for tenant: ${tenant_id}`)
    }
  }
}

/**
 * AI Event Processor
 * 
 * Integrates with the EventStore to automatically process events
 * through AI agents when they're committed.
 */
export class AIEventProcessor {
  private readonly agentManager: AIAgentManager
  private readonly eventStore: EventStore<any, GameEvent>
  private readonly subscriptions = new Map<string, () => void>() // tenant:aggregate → unsubscribe

  constructor(eventStore: EventStore<any, GameEvent>) {
    this.eventStore = eventStore
    this.agentManager = new AIAgentManager(eventStore)
  }

  /**
   * Start processing events for a specific tenant and aggregate
   */
  startProcessing(tenant_id: string, aggregate_id: string): void {
    // Subscribe to event store changes
    const unsubscribe = this.eventStore.subscribe(
      tenant_id,
      aggregate_id,
      async () => {
        const events = this.eventStore.getLog(tenant_id, aggregate_id)
        await this.agentManager.processEvents(tenant_id, aggregate_id, events)
      }
    )

    // Store unsubscribe function for cleanup
    const key = `${tenant_id}:${aggregate_id}`
    this.subscriptions.set(key, unsubscribe)

    console.log(`🤖 [AI] Started processing for tenant: ${tenant_id}, aggregate: ${aggregate_id}`)

    // Process existing events immediately
    const existingEvents = this.eventStore.getLog(tenant_id, aggregate_id)
    if (existingEvents.length > 0) {
      this.agentManager.processEvents(tenant_id, aggregate_id, existingEvents)
    }
  }

  /**
   * Stop processing events for a specific tenant and aggregate
   */
  stopProcessing(tenant_id: string, aggregate_id: string): void {
    const key = `${tenant_id}:${aggregate_id}`
    const unsubscribe = this.subscriptions.get(key)
    
    if (unsubscribe) {
      unsubscribe()
      this.subscriptions.delete(key)
      console.log(`🤖 [AI] Stopped processing for tenant: ${tenant_id}, aggregate: ${aggregate_id}`)
    }
  }

  /**
   * Get the agent manager for direct access
   */
  getAgentManager(): AIAgentManager {
    return this.agentManager
  }

  /**
   * Cleanup all subscriptions
   */
  cleanup(): void {
    for (const unsubscribe of this.subscriptions.values()) {
      unsubscribe()
    }
    this.subscriptions.clear()
    console.log('🤖 [AI] Cleaned up all event processor subscriptions')
  }
}

/**
 * Factory function to create AI integration
 */
export function createAIIntegration(eventStore: EventStore<any, GameEvent>): AIEventProcessor {
  return new AIEventProcessor(eventStore)
}
